// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Article struct {
	ID        int32
	Title     sql.NullString
	Content   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type ArticleCategory struct {
	ID         int32
	CategoryID int32
	ArticleID  int32
}

type Category struct {
	ID          int32
	Name        sql.NullString
	Description sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
